export enum WebSocketEvents {
  RANDOM_GAME = 'RANDOM_GAME',
  RANDOM_TEAMS = 'RANDOM_TEAMS',
  REFRESH_EVENTS = 'REFRESH_EVENTS',
  REFRESH_GAMES = 'REFRESH_GAMES',
  UPDATE_PLAYERS = 'UPDATE_PLAYERS',
}
