on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: make install
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
